/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { AnimationNode } from './lib/tree';
export namespace Components {
  interface AnimationContainer {
    'animation': (node: AnimationNode) => any;
    'state': string;
  }
  interface AppRoot {}
}
declare global {
  interface HTMLAnimationContainerElement
    extends Components.AnimationContainer,
      HTMLStencilElement {}
  var HTMLAnimationContainerElement: {
    prototype: HTMLAnimationContainerElement;
    new (): HTMLAnimationContainerElement;
  };
  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'animation-container': HTMLAnimationContainerElement;
    'app-root': HTMLAppRootElement;
  }
}
declare namespace LocalJSX {
  interface AnimationContainer {
    'animation'?: (node: AnimationNode) => any;
    'state'?: string;
  }
  interface AppRoot {}
  interface IntrinsicElements {
    'animation-container': AnimationContainer;
    'app-root': AppRoot;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'animation-container': LocalJSX.AnimationContainer &
        JSXBase.HTMLAttributes<HTMLAnimationContainerElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
    }
  }
}
